More eficient spelling in bash & zfs 2º drive

diff --git a/tux b/tux
--- a/tux
+++ b/tux
@@ -3,6 +3,7 @@
 # Version= 0.4.7
 
 # TODO: Improvements in the script
+# lsblk (how to detect second drive)
 # -> autologin in Devuan
 # In OpenSuse there is no android-tools lf trash-cli light by default (problema cc ST terminal)
 # MicrOS: git, stow, make (useradd -m, and visudo)
@@ -14,7 +15,7 @@
 # Void -> doas >>>>>>>> "permit $USER persist as root" to doas.conf
 # OpenBSD|Alpine -> bash
 
-exec &> >(tee -a "install.log") 2>install.error
+exec 1> >(tee "install.log") 2> >(tee "install.error")
 
 LVM_PASSWORD=""
 GIT_USERNAME="${USER}panzer"
@@ -34,7 +35,7 @@ CONFIGURE_PACKAGES()
   BTRFSPROGS=(    btrfs-progs               btrfs-progs           "$NA"                   btrfs-progs         btrfs-progs         btrfs-progs         btrfs-progs         btrfsprogs                  "$NA"                 "$NA"               )
   CRONTABS=(      python3-crontab           crontabs              crontabs                "$NA"               "$NA"               "$NA"               "$NA"               python3-crontab             py39-python-crontab   "$NA"               )
   DBUSX11=(       dbus-x11                  dbus-x11              dbus-x11                dbus                dbus                dbus-x11            dbus-x11            dbus-1-x11                  dbus                  dbus                )
-  DOAS=(          "$NA"                     opendoas              "$NA"                   opendoas            opendoas            opendoas            doas                opendoas                    doas                  "$NA"               )
+  DOAS=(          "$NA"                     "$NA"                 "$NA"                   "$NA"               "$NA"               opendoas            doas                opendoas                    doas                  "$NA"               )
   DUNST=(         dunst                     dunst                 "$NA"                   dunst               dunst               dunst               dunst               dunst                       dunst                 dunst               )
   EMACSNX=(	      emacs-nox		              emacs-nox		          emacs-nox		            emacs-nox	          emacs-nox	          emacs		            emacs-nox	          emacs-nox		                emacs-nox	            emacs-nosx          )
   FEH=(           feh                       feh                   "$NA"                   feh                 feh                 feh                 feh                 feh                         feh                   feh                 )
@@ -42,7 +43,7 @@ CONFIGURE_PACKAGES()
   FIREFOX=(       firefox-esr               firefox               firefox                 firefox             firefox             firefox             firefox             MozillaFirefox              firefox-esr           firefox-esr         )
   FLATPAK=(       flatpak                   flatpak               flatpak                 flatpak             flatpak             flatpak             flatpak             flatpak                     "$NA"                 "$NA"               )
   FZF=(           fzf                       fzf                   "$NA"                   fzf                 fzf                 fzf                 fzf                 fzf                         fzf                   fzf                 )
-  GCC=(           gcc                       gcc                   gcc                     gcc                 gcc                 gcc                 gcc                 gcc                         gcc                   gcc%11              )
+  GCC=(           gcc                       gcc                   gcc                     gcc                 gcc                 "$NA"               "$NA"               gcc                         gcc                   gcc%11              )
   GIFLIB=(        libgif-dev                giflib-devel          giflib-devel            giflib              giflib              giflib-devel        giflib-dev          giflib-devel                giflib                giflib              )
   GRUBBY=(        "$NA"                     grubby                grubby                  "$NA"               "$NA"               "$NA"               "$NA"               grubby                      "$NA"                 "$NA"               )
   IMAGEMAGICK=(   imagemagick               ImageMagick           ImageMagick             imagemagick         imagemagick         ImageMagick         imagemagick         ImageMagick                 ImageMagick7-nox11    ImageMagick         )
@@ -169,20 +170,20 @@ ALMALINUX_SETUP()
   echo "Defaults:$USER timestamp_timeout=60" | $SUDOAS tee /etc/sudoers.d/$USER
   $SUDOAS dnf update -y
   $SUDOAS dnf install -y epel-release
-  $SUDOAS dnf install -y --nogpgcheck https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %rhel).noarch.rpm
+  $SUDOAS dnf install -y --nogpgcheck https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-"$(rpm -E %rhel)".noarch.rpm
   $SUDOAS dnf config-manager --set-enabled crb
   $SUDOAS dnf install -y tar
 
   sh <(curl -L https://nixos.org/nix/install) --no-daemon
   sed -i 's/nixpkgs-unstable/nixos-22.11/g' .nix-channels
-  . $HOME/.nix-profile/etc/profile.d/nix.sh
+  $HOME/.nix-profile/etc/profile.d/nix.sh
   nix-channel --update
 
   nix-env -iA nixpkgs.nix nixpkgs.cacert
   nix-env -iA nixpkgs.android-tools nixpkgs.ffmpegthumbnailer nixpkgs.fzf nixpkgs.scrot nixpkgs.btrfs-progs nixpkgs.dunst nixpkgs.feh \
     nixpkgs.trash-cli nixpkgs.transmission-gtk nixpkgs.light \
     nixpkgs.picom nixpkgs.udiskie nixpkgs.python310Packages.adblock nixpkgs.ueberzug
-      . $HOME/.nix-profile/etc/profile.d/nix.sh
+      $HOME/.nix-profile/etc/profile.d/nix.sh
 
       $SUDOAS tee -a /etc/dnf/dnf.conf << EOF
 max_parallel_downloads=10
@@ -192,7 +193,7 @@ EOF
 
   $SUDOAS grubby --update-kernel=ALL --args=quiet
 
-  $SUDOAS dnf install https://zfsonlinux.org/epel/zfs-release-2-2$(rpm --eval "%{dist}").noarch.rpm
+  $SUDOAS dnf install https://zfsonlinux.org/epel/zfs-release-2-2"$(rpm --eval "%{dist}")".noarch.rpm
   $SUDOAS dnf install -y zfs
 }
 
@@ -229,7 +230,7 @@ ALPINE_SETUP()
   $SUDOAS grub-mkconfig -o /boot/grub/grub.cfg
 
   $SUDOAS setup-xorg-base
-  $SUDOAS rm -r /media/${cdrom,usb}
+  $SUDOAS rm -r /media/{cdrom,usb}
   $SUDOAS mkdir -p /media/Vault
 
   $SUDOAS mkdir /etc/udhcpc
@@ -250,13 +251,13 @@ ARCH_SETUP()
 {
   $SUDOAS $PKGINSTALL --needed base-devel git
   git clone https://aur.archlinux.org/trizen.git
-  cd trizen
+  cd trizen || exit
   makepkg -si
-  cd ..
+  cd || exit
   rm -R trizen
 
   curl -L https://archzfs.com/archzfs.gpg | $SUDOAS pacman-key -a -
-  $SUDOAS pacman-key --lsign-key $(curl -L https://git.io/JsfVS)
+  $SUDOAS pacman-key --lsign-key "$(curl -L https://git.io/JsfVS)"
   curl -L https://git.io/Jsfw2 | $SUDOAS tee /etc/pacman.d/mirrorlist-archzfs
 
   $SUDOAS tee -a /etc/pacman.conf << EOF
@@ -277,14 +278,14 @@ ARTIX_SETUP()
   ARCH_SETUP
   sh <(curl -L https://nixos.org/nix/install) --no-daemon
   sed -i 's/nixpkgs-unstable/nixos-22.11/g' .nix-channels
-  . $HOME/.nix-profile/etc/profile.d/nix.sh
+  $HOME/.nix-profile/etc/profile.d/nix.sh
   nix-channel --update
 
   nix-env -iA nixpkgs.nix nixpkgs.cacert
   nix-env -iA nixpkgs.android-tools nixpkgs.trash-cli nixpkgs.light nixpkgs.lf nixpkgs.stow nixpkgs.tig
-  . $HOME/.nix-profile/etc/profile.d/nix.sh
+  $HOME/.nix-profile/etc/profile.d/nix.sh
 
-  $SUDOAS sed -i 's/agetty.*/agetty --autologin $USER --noclear tty1 38400 linux' /etc/dinit.d/getty.d/tty1
+  $SUDOAS sed -i "s/agetty.*/agetty --autologin \$USER --noclear tty1 38400 linux" /etc/dinit.d/getty.d/tty1
 }
 
 CENTOS_SETUP()
@@ -323,7 +324,7 @@ FEDORA_SETUP()
 
   echo "Defaults:$USER timestamp_timeout=60" | $SUDOAS tee /etc/sudoers.d/$USER
   [ -x "$(command -v rpm-ostree)" ] && $SUDOAS rpm-ostree override remove zezere-ignition ignition dbus-parsec
-  $PKGINSTALL https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
+  $PKGINSTALL https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-"$(rpm -E %fedora)".noarch.rpm
   [ -x "$(command -v rpm-ostree)" ] && $SUDOAS rpm-ostree ex apply-live --allow-replacement
   [ -x "$(command -v rpm-ostree)" ] && $SUDOAS sed -i 's/none/stage/g' /etc/rpm-ostreed.conf
   $SUDOAS sed -i '2s/\/bin\/bash/\/usr\/bin\/zsh/g' /etc/passwd
@@ -346,7 +347,7 @@ EOF
   [ -x "$(command -v rpm-ostree)" ] && $SUDOAS sed -i 's/#Auto/Auto/g' /etc/rpm-ostreed.conf
   [ -x "$(command -v rpm-ostree)" ] && $SUDOAS systemctl enable rpm-ostreed-automatic.timer --now
 
-  [ ! -x "$(command -v rpm-ostree)" ] && $SUDOAS dnf install -y https://zfsonlinux.org/fedora/zfs-release-2-2$(rpm --eval "%{dist}").noarch.rpm
+  [ ! -x "$(command -v rpm-ostree)" ] && $SUDOAS dnf install -y https://zfsonlinux.org/fedora/zfs-release-2-2"$(rpm --eval "%{dist}")".noarch.rpm
   [ ! -x "$(command -v rpm-ostree)" ] && $SUDOAS dnf install -y kernel-devel
   [ ! -x "$(command -v rpm-ostree)" ] && $SUDOAS dnf install -y zfs
 }
@@ -366,10 +367,10 @@ linux_enable=YES
 #rpc_statd_enable="YES""
 EOF
 
+  DWMBLOCKS="$HOME/.config/suckless/dwmblocks"
   echo "kern.evdev.rcpt_mask=3" | $SUDOAS tee -a /etc/sysctl.conf
-  cd $HOME/.config/suckless/dwmblocks; cp Makefile.bsd Makefile; $SUDOAS make install clean
-  #cd $HOME/.config/suckless/sxiv; $SUDOAS make install clean
-  cd $HOME
+  cp $DWMBLOCKS/Makefile.bsd $DWMBLOCKS/Makefile; $SUDOAS make $DWMBLOCKS install clean
+  #$SUDOAS make -C $HOME/.config/suckless/sxiv install clean
 }
 
 NIXOS_SETUP()
@@ -377,7 +378,7 @@ NIXOS_SETUP()
   mkdir .config
   curl -L https://raw.githubusercontent.com/sorathpanzer/nixos/main/configuration.nix > configuration.nix
   #sed -i s/luks-/$(lsblk -l | grep luks | awk '{print $1}')/g configuration.nix
-  sed -i s/HOSTID/$(head -c 8 /etc/machine-id)/g configuration.nix
+  sed -i s/HOSTID/"$(head -c 8 /etc/machine-id)"/g configuration.nix
   $SUDOAS cp configuration.nix /etc/nixos/configuration.nix
   $SUDOAS nixos-rebuild boot
 }
@@ -405,7 +406,7 @@ OPENSUSE_SETUP()
 
   $PKGINSTALL make ncurses-devel posix_cc
 
-  TUMBLEWEED=$(cat /etc/os-release | grep ^NAME= | cut -d '=' -f2 | awk '{print $2}' | tr -d '"')
+  TUMBLEWEED=$(grep ^NAME= /etc/os-release | cut -d '=' -f2 | awk '{print $2}' | tr -d '"')
   if [ $TUMBLEWEED = Tumbleweed ]; then
     $SUDOAS zypper install -y android-tools
     $SUDOAS zypper addrepo https://download.opensuse.org/repositories/filesystems/openSUSE_Tumbleweed/filesystems.repo
@@ -446,9 +447,9 @@ INSTALL_PACKAGES()
     ${ADBLOCK[$POS]} ${ANDROIDTOOLS[$POS]} ${BTRFSPROGS[$POS]} ${CRONTABS[$POS]} ${DBUSX11[$POS]} ${DUNST[$POS]} ${FEH[$POS]} ${FFTHUMBNAILER[$POS]} ${FIREFOX[$POS]} \
     ${FLATPAK[$POS]} ${FZF[$POS]} ${GIFLIB[$POS]} ${GRUBBY[$POS]} ${IMAGEMAGICK[$POS]} ${LIBXFT[$POS]} ${IMLIB2[$POS]} ${LIBREOFFICE[$POS]} ${LF[$POS]} ${NFSUTILS[$POS]} \
     ${LIGHT[$POS]} ${LIBEXIF[$POS]} ${LIBX11[$POS]} ${LIBXINERAMA[$POS]} ${LMSENSORS[$POS]} ${NTFS3G[$POS]} ${PANDOCPDF[$POS]} ${PICOM[$POS]} ${POPPLERUTILS[$POS]} \
-    ${PAUTILS[$POS]} ${PYTHON[$POS]} ${PYTHON3PIP[$POS]} ${PYTHON3SIX[$POS]} ${QEMU[$POS]} ${SCROT[$POS]} ${SOX[$POS]} ${STOW[$POS]} ${TIG[$POS]} ${TRASHCLI[$POS]} \
+    ${PAUTILS[$POS]} ${PYTHON[$POS]} ${PYTHON3PIP[$POS]} ${PYTHON3SIX[$POS]} ${QEMU[$POS]} ${SCROT[$POS]} ${SOX[$POS]} ${STOW[$POS]} ${TIG[$POS]} ${TRASHCLI[$POS]} ${GCC[$POS]} \
     ${TELEGRAM[$POS]} ${UDISKIE[$POS]} ${UEBERZUG[$POS]} ${XDOTOOL[$POS]} ${XINPUT[$POS]} ${XF86INTEL[$POS]} ${XORGSERVER[$POS]} ${XINIT[$POS]} ${XRANDR[$POS]} ${LIBXRESDEV[$POS]} \
-    ${XRDB[$POS]} ${XSET[$POS]} ${YOUTUBEDL[$POS]} ${ZATHURA[$POS]} ${ZATHURAPDF[$POS]} ${OVMF[$POS]} ${NMTUI[$POS]} ${QUTEBROWSER[$POS]} ${EMACSNX[$POS]} ${ZFS[$POS]}
+    ${XRDB[$POS]} ${XSET[$POS]} ${YOUTUBEDL[$POS]} ${ZATHURA[$POS]} ${ZATHURAPDF[$POS]} ${OVMF[$POS]} ${NMTUI[$POS]} ${QUTEBROWSER[$POS]} ${EMACSNX[$POS]} ${ZFS[$POS]} ${DOAS[$POS]}
 
   [ -x "$(command -v rpm-ostree)" ] && $SUDOAS rpm-ostree ex apply-live --allow-replacement
 
@@ -489,25 +490,23 @@ CONFIGURE_HOME()
   cp $HOME/.config/suckless/st-0.9/config.$MK $HOME/.config/suckless/st-0.9/config.mk
 
   if [ $RELEASE != NixOS ]; then
-    cd $HOME/.config/suckless/dwmblocks; make install clean
-    cd $HOME/.config/suckless/sxiv; make install clean
-    cd $HOME/.config/suckless/dwm-6.4; make install clean
-    cd $HOME/.config/suckless/dmenu-5.2; make install clean
+    make -C $HOME/.config/suckless/dwmblocks install clean
+    make -C $HOME/.config/suckless/sxiv install clean
+    make -C $HOME/.config/suckless/dwm-6.4 install clean
+    make -C $HOME/.config/suckless/dmenu-5.2 install clean
     [ -x "$(command -v zypper)" ] && $SUDOAS sed -i 's/#CC/CC/g' ~/.config/suckless/st-0.9/config.mk
-    cd $HOME/.config/suckless/st-0.9; make install clean
-    cd
+    make -C $HOME/.config/suckless/st-0.9 install clean
   fi
 
   if [ $RELEASE != FreeBSD ]; then
-    NVME=$(lsblk -l | grep sda | head -n 1 | awk '{print $1}')
-    SDA=$(lsblk -l | grep sda | head -n 1 | awk '{print $1}')
 
-    if [ ! -z $LVM_PASSWORD ]; then
+    if [ -n "$LVM_PASSWORD" ]; then
       echo "Open vault password:"
-      mkdir Vault
-      echo -n "$LVM_PASSWORD" | $SUDOAS cryptsetup open --type luks /dev/sda1 Vault
-      $SUDOAS mount /dev/mapper/Vault Vault
-      rsync -avrop Vault/Documentos/BackHome/ /home/$USER
+      mkdir /media/Vault
+      $SUDOAS modprobe zfs
+      echo -n "$LVM_PASSWORD" | $SUDOAS zpool import -l -R /media/Vault Legion
+      $SUDOAS zfs mount Legion/Vault
+      rsync -avrop /media/Vault/BackHome/ /home/$USER
     fi
   fi
 
@@ -559,9 +558,8 @@ EOF
   echo zfs | $SUDOAS tee /etc/modules-load.d/zfs.conf
 
   if ! [[ $RELEASE = Arch || $RELEASE = Void || $RELEASE = AlmaLinux ]]; then
-    git clone https://github.com/sorathpanzer/ueberzug.git && cd ueberzug
-    pip install --user -e .
-    cd
+    git clone https://github.com/sorathpanzer/ueberzug.git
+    pip install --user -e ./ueberzug
     $SUDOAS rm -R ueberzug
   fi
 
@@ -611,4 +609,4 @@ case "${RELEASE}" in
     NIXOS_SETUP ;;
 esac
 
-cat install.error | grep error
+grep error install.error
